### PR TITLE
Added docker build arguments

### PR DESCRIPTION
**Pull request by liyinan926**
@kimoonkim @foxish

### CODE REVIEW

**Comment by liyinan926** [comment]
I verified manually that build of spark-base worked with this fix.

**Comment by liyinan926** [comment]
We need this to be merged to fix the scheduled runs.

**Comment by foxish** [comment]
Lgtm, OK to merge if manual tests passed.

**Comment by liyinan926** [comment]
Yes, manually ran the tests and all passed.

**Comment by liyinan926** [comment]
I will merge once https://github.com/apache/spark/pull/20170 gets merged.

**Comment by foxish** [comment]
Sorry - I thought you wanted me to merge. 
But should be ok either way - since tests are broken anyway for now - we'll see the effects only after that PR merges.

**Comment by liyinan926** [comment]
No worries. The scheduled run should be back to normal after the upstream pr is merged.

**Pull request merged**
